version: '3'
services:
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - batch

  artemis:
    build: ./activemq
    container_name: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
#    networks:
#      - batch

networks:
  batch:
    driver: bridge